# print("こんにちは")
# print("Hello World".upper())
# print("Hello World".lower())
# print("Hello World.I am Tack.".upper().split(" "))
# x = "Hello World"
# # print(x)
# print(x.upper())
# x = "Good morning"
# x = x.upper()
# print(x)
# print(["Hello"])
# print(type(["Hello"]))
# print(["Hello","World"])
# print(["a","b","c","d","e"])
# print(["a","b","c",1,2,3])
# print(["a","b",["c",1,2,3]])
# print(["a","b","c","d","e"][0])
# print(["a","b","c"][2])
# print(["a","b",["c",1,2,3]][2])
# print(["a","b",["c",1,2,3]][2][0])
# print(["a","b","c","d","e"][-1])
# print(["a","b","c","d","e"][10])
# print(["a","b","c",[0,1,2,3]][3][1:3])
# x = ["a","b","c"]
# x.append("d")
# print(x)
# print(("Hello"))
# print(type(("Hello")))
# print(("Hello",))
# print(type(("Hello",)))
# print(("a","b","c","d","e")[2])
# print((1,2,3,"a","b","c")[-2])
# print((1,2,3,"a","b","c")[2:5])
# print((1,2,3,["a","b","c"]))
# for a in{"a":"apple","b":"ball","c":"cat"}:
#     print(a)
<<<<<<< HEAD
# print("unko")
# print("kosdkoask")
=======
print("unko")
# print("kosdkoask")
# print("korokoro")
>>>>>>> 9cc8f25ec18f96bcc447cc528a4be9e03f6ea271
